### ISSUE TITLE
IllegalArgumentException: Bitmap could not be decoded from the Uri

### ISSUE THREAD

**Issue by galadril** [Frosch2010/uCrop-n-Edit#4]
Im trying to crop an image which i get from the google photo picker:

```
ActivityResultLauncher<PickVisualMediaRequest> pickMedia =
                registerForActivityResult(new ActivityResultContracts.PickVisualMedia(), uri -> {
                    if (uri != null) {
                        String path = uri.getPath();
                        String imagePath = activity.getCacheDir() + "/" + path.substring(path.lastIndexOf("/") + 1);
                        Uri destinationUri = Uri.parse(imagePath);
                        UCrop.of(uri, destinationUri)
                                .withAspectRatio(1, 1)
                                .withMaxResultSize(500, 500)
                                .start(context, cropMedia);
                    } else {
                        Log.d("PhotoPicker", "No media selected");
                    }
                });
```

But uCrop-n-Edit  is failing on my destination uri:

```
java.lang.IllegalArgumentException: Bitmap could not be decoded from the Uri: [/data/user/0/com.app.namespace/cache/1000004510]
  at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.kt:103)
  at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.kt:26)
  at android.os.AsyncTask$3.call(AsyncTask.java:394)
  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
  at java.lang.Thread.run(Thread.java:1012)
  Caused by: java.io.FileNotFoundException: No content provider: /data/user/0/com.app.namespace/cache/1000004510
  at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2015)
  at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
  at android.content.ContentResolver.openInputStream(ContentResolver.java:1520)
  at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.kt:84)
  at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.kt:26) 
  at android.os.AsyncTask$3.call(AsyncTask.java:394) 
  at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
  at java.lang.Thread.run(Thread.java:1012) 
```
  
any ideas what i'm doing wrong?

**Comment by Frosch2010** [comment]
> Caused by: java.io.FileNotFoundException: No content provider: /data/user/0/com.app.namespace/cache/1000004510
The error suggests me that the image you want to open is not in your cache folder. I guess you are missing the file ending. Is 1000004510 a .jpg or what is it?

I guess `path.substring(path.lastIndexOf("/") + 1)` is cutting out the file ending.

I hope that helps :)
